name: CoSketch frontend

on: 
  push: 
    branches: [ production ]
    paths: 
      - 'apps/cosketch-frontend/**'
      - 'packages/**'
      - '.github/workflows/cd_frontend.yml'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code frontend
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend.prod.Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_HTTP_URL=${{ secrets.NEXT_PUBLIC_HTTP_URL }}
            NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }}
          tags: |
            narsibhati6545/cosketch-frontend:${{ github.sha }} 
            narsibhati6545/cosketch-frontend:latest

#       - name: Deploy to VM
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: "${{secrets.HOST_IP}}"
#           username: "ubuntu"
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             sudo docker pull narsibhati6545/cosketch-frontend:latest

#             if sudo docker ps -a --format '{{.Names}}' | grep -q "^cosketch-frontend$"; then
#               sudo docker stop cosketch-frontend
#               sudo docker rm cosketch-frontend
#             fi

#             sudo docker run -d \
#               --name cosketch-frontend \
#               -p 3000:3000 \
#               --restart always \
#               narsibhati6545/cosketch-frontend:latest

#             echo "CoSketch frontend deployed successfully!"
#             sudo docker image prune -f --filter "until=24h"